Add checks for semantic python versions

diff --git a/setup-env b/setup-env
--- a/setup-env
+++ b/setup-env
@@ -39,6 +39,14 @@ python_versions() {
   pyenv versions --bare --skip-aliases --skip-envs
 }
 
+check_semantic_version() {
+  local version=$1
+  local regex="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\$"
+
+  # Use Perl for regex matching and output true or false
+  echo "$version" | perl -ne "exit(!/$regex/)"
+}
+
 # Flag to force deletion and creation of virtual environment
 FORCE=0
 
@@ -103,16 +111,18 @@ while true; do
     -p | --python-version)
       PYTHON_VERSION="$2"
       shift 2
-      # Check the Python versions being passed in.
-      if [ -n "${PYTHON_VERSION+x}" ]; then
-        if python_versions | grep -E "^${PYTHON_VERSION}$" > /dev/null; then
-          echo Using Python version "$PYTHON_VERSION"
-        else
-          echo Error: Python version "$PYTHON_VERSION" is not installed.
-          echo Installed Python versions are:
-          python_versions
-          exit 1
-        fi
+      # Validate the semantic version format
+      if ! check_semantic_version "$PYTHON_VERSION"; then
+        echo "Error: The specified Python version $PYTHON_VERSION does not follow the semantic versioning standard."
+        echo "Example of a valid version: 3.8.1, 3.8.1-alpha.1, or 3.8.1+20130313144700"
+        exit 1
+      elif ! python_versions | grep -E "^${PYTHON_VERSION}$" > /dev/null; then
+        echo "Error: Python version $PYTHON_VERSION is not installed."
+        echo "Installed Python versions are:"
+        python_versions
+        exit 1
+      else
+        echo "Using Python version $PYTHON_VERSION"
       fi
       ;;
     -v | --venv-name)
@@ -181,14 +191,7 @@ if [ $LIST_VERSIONS -ne 0 ]; then
   python_versions
   read -r -p "Enter the desired Python version: " PYTHON_VERSION
   # Check the Python versions being passed in.
-  if [ -n "${PYTHON_VERSION+x}" ]; then
-    if python_versions | grep -E "^${PYTHON_VERSION}$" > /dev/null; then
-      echo Using Python version "$PYTHON_VERSION"
-    else
-      echo Error: Python version "$PYTHON_VERSION" is not installed.
-      exit 1
-    fi
-  fi
+  check_semantic_version "$PYTHON_VERSION"
 fi
 
 # Remove any lingering local configuration.
